services:
  - type: web
    name: propsedge-api
    env: node
    plan: free
    rootDir: server
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: BUILD_TAG
        value: PROPS-EDGE_CRYSTAL_EDITION_WORLD_GENESIS
    autoDeploy: true

  - type: web
    name: propsedge-client
    env: static
    plan: free
    rootDir: client
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
    routes:
      - type: rewrite
        source: /api/*
        destination: https://propsedge-api.onrender.com